version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - docker --version
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - aws --version
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 062241367565.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=062241367565.dkr.ecr.us-east-1.amazonaws.com/spring
      - CONTAINER_NAME=spring
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      # Build
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      # Post Build
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Write the image definitions file for ECS
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions
artifacts:
  files: 
      - imagedefinitions.json
      - imagedefinitions